version: '3'
services:
  nginx:
    build: ./nginx
    links:
      - node:node
    ports:
      - "80:80"
  node:
    build: .
    command: node server.js
    ports:
      - "3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - ELASTIC_URI=${ELASTIC_URI}
